### ISSUE TITLE
require('url') breaks validation in Firefox

### ISSUE THREAD

**Issue by paulrouget** [mozilla/firefox-app-validator-manifest#40]
We already have a "url" module in Firefox. And it doesn't match Node's API.

What would be great is to always use local imports. Something like: `require('./libwrappers/url')`. The content of `libwrappers` would be different for Node and Firefox. For node code, `libwrappers/url` would just redirector to `url`. Firefox side, we would wrap Firefox local API to Node's API.

**Comment by paulrouget** [comment]
We also want these wrappers to work for other validation mechanism (node-firefox-app-validator-icons for example). So we might want to import a parent directory that could be shared by any code: `require('../libwrappers/url')`

**Comment by paulrouget** [comment]
Something like that:

https://github.com/paulrouget/node-firefox-app-validator-manifest/compare/firefox
https://github.com/paulrouget/node-firefox-app-validator-icons/compare/firefox

**Comment by operatorjen** [comment]
Handled as per example https://github.com/mozilla/firefox-app-validator-manifest/blob/master/README.md#checking-your-manifest-an-example (libwrappers in this case is in this module and not https://github.com/mozilla/firefox-app-validator-central because the module is only called in this module scope. If someone were to only use this module instead of central, then it would also work).

If you prefer it to be moved up to central, we can do that but I don't think it's harmful in either option - but more modular in this current context.
